services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: tagora
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - tagora_network
    restart: always

networks:
  tagora_network:
    driver: bridge
